FROM node:20-alpine AS base
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend ./
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=base /app/dist /usr/share/nginx/html
EXPOSE 80
